#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d main term game code shelf web media chat docs

bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## Self added
# General
xrandr --output Virtual-1 --mode 1920x1080 --primary
setxkbmap -model pc105 -layout us -variant altgr-intl
polybar -r modern &
nitrogen --restore
picom -b --experimental-backends
