#! /bin/sh

# Autostart
#sh $HOME/.config/bspwm/autostart.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

function general_setup() {
    bsp-layout set tall 1
    bsp-layout set tall 2
    bsp-layout set tall 3
    bsp-layout set tall 4
    bsp-layout set tall 5
    bsp-layout set tall 6
    bsp-layout set tall 7
    # bsp-layout set tall 8
    # bsp-layout set tall 9

    bspc config border_width        3
    bspc config window_gap          8

    bspc config split_ratio          0.52
    bspc config borderless_monocle   true
    bspc config gapless_monocle      true

    bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
    bspc rule -a Vivaldi-stable desktop ='1'
    bspc rule -a teams desktop ='6'
    bspc rule -a wgc.exe state=floating
    bspc rule -a steam_app_794260 state=fullscreeen
    #bspc rule -a worldoftanks.exe state=fullscreen follow=on
    bspc rule -a epicgameslauncher.exe state=floating follow=on
    #bspc rule -a War Thunder (Vulkan, 64bit) state=floating follow=on
    bspc rule -a discord desktop='8'
    bspc rule -a mplayer2 state=floating
    bspc rule -a Kupfer.py focus=on
    bspc rule -a Screenkey manage=off
}

if ! xrandr | grep 'eDP connected'; then
    echo "home setup"
    bspc monitor DP-2 -d    1 2 3 7
    bspc monitor HDMI-0 -d  4 5 6
    bspc monitor DP-5 -d    8 9
    general_setup
    xrandr --output HDMI-0 --mode 1920x1080 --pos 3610x300 --rotate normal --output DP-2 --primary --mode 2560x1080 --rate 144.0 --pos 1050x300 --rotate normal --output DP-5 --mode 1680x1050 --pos 0x0 --rotate right --output USB-C-0 --off &
else
    if xrandr --listactivemonitors | grep 'DisplayPort-2' &&
    xrandr --listactivemonitors | grep 'DisplayPort-4'; then
        echo "usual work setup"
        bspc monitor DisplayPort-2 -d    1 2 3 4 5
        bspc monitor DisplayPort-4 -d    6 7 8 9
        general_setup
        xrandr --output eDP --off --output DisplayPort-0 --off --output DisplayPort-1 --off --output DisplayPort-2 --primary --mode 2560x1080 --pos 0x0 --rotate normal --output DisplayPort-3 --off --output DisplayPort-4 --mode 1920x1080 --pos 2560x0 --rotate normal --output DisplayPort-5 --off --output DisplayPort-6 --off &
    elif xrandr --listactivemonitors | grep 'eDP' &&
    xrandr --listactivemonitors | grep 'DisplayPort-2' &&
    xrandr --listactivemonitors | grep 'DisplayPort-4'; then
        echo "extended work setup"
        general_setup
    elif xrandr --listactivemonitors | grep 'DisplayPort-0' &&
    xrandr --listactivemonitors | grep 'DisplayPort-1'; then
        echo "office setup"
        xrandr --output eDP --off --output DisplayPort-0 --mode 2560x1440 --pos 0x0 --rotate normal --output DisplayPort-1 --mode 2560x1440 --pos 2560x0 --rotate normal --output DisplayPort-2 --off --output DisplayPort-3 --off
        bspc monitor DisplayPort-1 -d    1 2 3 4 5
        bspc monitor DisplayPort-0 -d    6 7 8 9
        general_setup
    else xrandr --listactivemonitors | grep 'eDP'
        echo "simple work setup"
        bspc monitor eDP -d 1 2 3 4 5 6 7 8 9
        general_setup
    fi
fi

~/.config/autostart.sh