theme = "tokyonight"

[editor]
bufferline = "always"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = "↪ "  # set wrap-indicator to "" to hide it

[keys.normal]
u = "insert_mode"
U = "insert_at_line_start"

l = "undo"
L = "redo"

k = "search_next"
K = "search_prev"

f = "move_next_word_end"
F = "move_next_long_word_end"

h = "find_next_char"
H = "find_prev_char"

j = "open_below"
J = "open_above"

n = "move_char_left"
i = "move_line_up"
e = "move_line_down"
o = "move_char_right"
C-i = "page_up"
C-e = "page_down"
C-I = "half_page_up"
C-E = "half_page_down"
"C-/" = "toggle_comments"
esc = ["collapse_selection", "keep_primary_selection"]
y = "yank_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"

[keys.normal.g]
n = "goto_line_start"
o = "goto_line_end"
k = "goto_next_buffer"

[keys.select]
n = "extend_char_left"
i = "extend_line_up"
e = "extend_line_down"
o = "extend_char_right"
y = "yank_to_clipboard"
p = "replace_selections_with_clipboard"

f = "extend_next_word_end"
F = "extend_next_long_word_end"

[keys.insert]
C-n = "move_char_left"
C-i = "move_line_up"
C-e = "move_line_down"
C-o = "move_char_right"

[editor.cursor-shape]
insert = "bar"

[keys.normal.space]
x = ":buffer-close"
